In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
df.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

### Subsets

In [9]:
setosa_sub = df[df.Species=='Iris-setosa']
setosa_sub.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
versicolor_sub = df[df.Species=='Iris-versicolor']
versicolor_sub.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor

In [11]:
virginica_sub = df[df.Species=='Iris-virginica']
virginica_sub.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica

### Sort data

In [12]:
df.sort_values('PetalLengthCm')

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
22,23,4.6,3.6,1.0,0.2,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
35,36,5.0,3.2,1.2,0.2,Iris-setosa
36,37,5.5,3.5,1.3,0.2,Iris-setosa
...,...,...,...,...,...,...
131,132,7.9,3.8,6.4,2.0,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica

### Merge subsets

In [13]:
merged_data = pd.merge(versicolor_sub,versicolor_sub)
merged_data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,51,7.0,3.2,4.7,1.4,Iris-versicolor
1,52,6.4,3.2,4.5,1.5,Iris-versicolor
2,53,6.9,3.1,4.9,1.5,Iris-versicolor
3,54,5.5,2.3,4.0,1.3,Iris-versicolor
4,55,6.5,2.8,4.6,1.5,Iris-versicolor
5,56,5.7,2.8,4.5,1.3,Iris-versicolor
6,57,6.3,3.3,4.7,1.6,Iris-versicolor
7,58,4.9,2.4,3.3,1.0,Iris-versicolor
8,59,6.6,2.9,4.6,1.3,Iris-versicolor
9,60,5.2,2.7,3.9,1.4,Iris-versicolor
10,61,5.0,2.0,3.5,1.0,Iris-versicolor
11,62,5.9,3.0,4.2,1.5,Iris-versicolor
12,63,6.0,2.2,4.0,1.0,Iris-versicolor
13,64,6.1,2.9,4.7,1.4,Iris-versicolor
14,65,5.6,2.9,3.6,1.3,Iris-versicolor
15,66,6.7,3.1,4.4,1.4,Iris-versicolor
16,67,5.6,3.0,4.5,1.5,Iris-versicolor
17,68,5.8,2.7,4.1,1.0,Iris-versicolor
18,69,6.2,2.2,4.5,1.5,Iris-versicolor
19,70,5.6,2.5,3.9,1.1,Iris-versicolor
20,71,5.9,3.2,4.8,1.8,Iris-versicolor
21,72,6.1,2.8,4.0,1.3,Iris-versicolor
22,73,6.3,2.5,4.9,1.5,Iris-versicolor
23,74,6.1,2.8,4.7,1.2,Iris-versicolor
24,75,6.4,2.9,4.3,1.3,Iris-versicolor
25,76,6.6,3.0,4.4,1.4,Iris-versicolor
26,77,6.8,2.8,4.8,1.4,Iris-versicolor
27,78,6.7,3.0,5.0,1.7,Iris-versicolor
28,79,6.0,2.9,4.5,1.5,Iris-versicolor
29,80,5.7,2.6,3.5,1.0,Iris-versicolor
30,81,5.5,2.4,3.8,1.1,Iris-versicolor
31,82,5.5,2.4,3.7,1.0,Iris-versicolor
32,83,5.8,2.7,3.9,1.2,Iris-versicolor
33,84,6.0,2.7,5.1,1.6,Iris-versicolor
34,85,5.4,3.0,4.5,1.5,Iris-versicolor
35,86,6.0,3.4,4.5,1.6,Iris-versicolor
36,87,6.7,3.1,4.7,1.5,Iris-versicolor
37,88,6.3,2.3,4.4,1.3,Iris-versicolor
38,89,5.6,3.0,4.1,1.3,Iris-versicolor
39,90,5.5,2.5,4.0,1.3,Iris-versicolor
40,91,5.5,2.6,4.4,1.2,Iris-versicolor
41,92,6.1,3.0,4.6,1.4,Iris-versicolor
42,93,5.8,2.6,4.0,1.2,Iris-versicolor
43,94,5.0,2.3,3.3,1.0,Iris-versicolor
44,95,5.6,2.7,4.2,1.3,Iris-versicolor
45,96,5.7,3.0,4.2,1.2,Iris-versicolor
46,97,5.7,2.9,4.2,1.3,Iris-versicolor
47,98,6.2,2.9,4.3,1.3,Iris-versicolor
48,99,5.1,2.5,3.0,1.1,Iris-versicolor
49,100,5.7,2.8,4.1,1.3,Iris-versicolor

### Transpose

In [25]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
Id,1,2,3,4,5,6,7,8,9,10,...,141,142,143,144,145,146,147,148,149,150
SepalLengthCm,5.1,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
SepalWidthCm,3.5,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,...,3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
PetalLengthCm,1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,...,5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
PetalWidthCm,0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,...,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
Species,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica

### Melting

In [16]:
melted_df = pd.melt(df, id_vars=['Species'], value_vars=['SepalLengthCm','SepalWidthCm'])

In [17]:
melted_df

            Species       variable  value
0       Iris-setosa  SepalLengthCm    5.1
1       Iris-setosa  SepalLengthCm    4.9
2       Iris-setosa  SepalLengthCm    4.7
3       Iris-setosa  SepalLengthCm    4.6
4       Iris-setosa  SepalLengthCm    5.0
..              ...            ...    ...
295  Iris-virginica   SepalWidthCm    3.0
296  Iris-virginica   SepalWidthCm    2.5
297  Iris-virginica   SepalWidthCm    3.0
298  Iris-virginica   SepalWidthCm    3.4
299  Iris-virginica   SepalWidthCm    3.0

[300 rows x 3 columns]

In [23]:
pivot_df = pd.pivot_table(df,values=['SepalWidthCm','SepalLengthCm'], index='Species', aggfunc="mean")

In [24]:
pivot_df

                 SepalLengthCm  SepalWidthCm
Species
Iris-setosa              5.006         3.418
Iris-versicolor          5.936         2.770
Iris-virginica           6.588         2.974